### ISSUE TITLE
S3 secret in code 

### ISSUE THREAD

**Issue by unixdespair** [binkocd/s3archiver#1]
Hi, I know this has been up here for over four years and the account has since been deleted, but checking in AWS access keys and secrets in a public repo isn’t great. Please delete them.

**Comment by unixdespair** [comment]
https://github.com/binkocd/s3archiver/blob/a81376f42928816d9c4a914f21a8935bd767f8d6/lists3archives.py

**Comment by binkocd** [comment]
I don't see keys in this repo. Please explain.

**Comment by unixdespair** [comment]
Hi, from the original commit I believe.

https://github.com/binkocd/s3archiver/blob/a81376f42928816d9c4a914f21a8935bd767f8d6/lists3archives.py

**Comment by binkocd** [comment]
Ok, so it's an out of date commit and the key has long since been removed. Maybe go find someone else to bother?
